  install.packages("sqldf")
  install.packages("gsubfn")
  install.packages("proto")
  install.packages("RSQLite")
  library(sqldf)
  library(gsubfn)
  library(proto)
  library(RSQLite)
  
  
events <- subset(events,select = -text)
pregunta_inicial <- subset(events,select = c(side, id_odsp, event_type, is_goal))
pregunta_inicial <- sqldf('SELECT * FROM pregunta_inicial WHERE event_type = 1')
pregunta_inicial <- subset(pregunta_inicial,select=-event_type)
prueba <- sqldf('SELECT id_odsp,count(is_goal) as tiros_totales FROM pregunta_inicial GROUP BY id_odsp')
conjuntacion <- sqldf('SELECT * FROM pregunta_inicial NATURAL JOIN prueba')
prueba <- sqldf('SELECT id_odsp,count(is_goal) as goles FROM pregunta_inicial WHERE is_goal=1 GROUP BY id_odsp')
conjuntacion <- sqldf('SELECT * FROM conjuntacion NATURAL JOIN prueba')
prueba <- sqldf('SELECT id_odsp,count(is_goal) as golLocal FROM pregunta_inicial WHERE is_goal=1 AND side = 1 GROUP BY id_odsp')
conjuntacion <- sqldf('SELECT * FROM conjuntacion NATURAL JOIN prueba')
prueba <- sqldf('SELECT id_odsp,count(is_goal) as golVisitante FROM pregunta_inicial WHERE is_goal=1 AND side = 2 GROUP BY id_odsp')
conjuntacion <- sqldf('SELECT * FROM conjuntacion NATURAL JOIN prueba')
prueba <- sqldf('SELECT id_odsp,count(is_goal) as tirosLocal FROM pregunta_inicial WHERE side = 1 GROUP BY id_odsp')
conjuntacion <- sqldf('SELECT * FROM conjuntacion NATURAL JOIN prueba')
prueba <- sqldf('SELECT id_odsp,count(is_goal) as tirosVisitante FROM pregunta_inicial WHERE side = 2 GROUP BY id_odsp')
conjuntacion <- sqldf('SELECT * FROM conjuntacion NATURAL JOIN prueba')
conjuntacion <- subset(conjuntacion, select = -side)
conjuntacion <- subset(conjuntacion, select = -is_goal)
View(conjuntacion)
conjuntacion <- sqldf('SELECT distinct * from conjuntacion')
View(conjuntacion)
